# Learn_Numpy

In [1]:
# numpy is a libray or an module, classes and fn are predefined 
# pip install numpy 
# it deals well with array 
# array is 10 times faster than list, coz numpy libray is made up of C/C++ 
# list can be is used when u want to do genral purpose operation
# eg. you have 10k items and u r adding +2 then ok but if u have a big data set
# and u want to caluclate %, mean bif formula list will take 5 min and numpy will take less than 1 min
# numpy has maintains time complexity 
# has all the fn to deal with the array 

import numpy as np
print("numpy is imported")

numpy is imported


In [2]:
ls = [46, 38, 58, 61, 69, 49, 72, 74]
print(ls)

[46, 38, 58, 61, 69, 49, 72, 74]


In [3]:
ls = [46, 38, 58, 61, 69, 49, 72, 74]
arr = np.array(ls)
arr
# it is a one dimensional array

array([46, 38, 58, 61, 69, 49, 72, 74])

In [4]:
type(arr)
# ndarray - N dimentional array 

numpy.ndarray

In [5]:
arr + 5
# has done increment as 5

array([51, 43, 63, 66, 74, 54, 77, 79])

In [6]:
arr.ndim 
# ndim is fn - tells the no. of dimentions 
# 1 means - no. of dimensions
# [[], [], [], [], [], [], [], [],]------ two dimensions

1

In [7]:
# conitnous mememory allocations 
arr.dtype # will tell the data type its int

dtype('int32')

### For float value 

In [8]:
ls = [46, 38, 58, 61, 69, 49, 72, 74, 42.5]
arr = np.array(ls)
arr
# it is a one dimensional array
# if i add one as float then it will make every value as float

array([46. , 38. , 58. , 61. , 69. , 49. , 72. , 74. , 42.5])

In [9]:
arr.dtype

dtype('float64')

### For string Value 

In [10]:
ls = [46, 38, 58, 61, 69, 49, 72, 74, "upflairs"]
arr = np.array(ls)
arr
# will all the value as string

array(['46', '38', '58', '61', '69', '49', '72', '74', 'upflairs'],
      dtype='<U11')

In [11]:
arr.dtype

dtype('<U11')

In [12]:
# array -------
# collection of similar item
# arr has continious memory allocation

# int arr[10] = {............}
# this means we r storing 10 elements, and int takes 4 byte memory ------ 4*10 = 40 bytes arr requests for memaory allocation 
# a block of storange for 40 bytes is allocated in ur computer 

### ----------------------------------------------------------

In [13]:
ls = [41,33,53,56,64,44,67]
arr = np.array(ls)
arr[2]
# if acces any element like this what will be the time complexity of the arr 
# time complexity is or 1 order of 1
# --------------------------------------------------------------------------------------------
# first_item_address + (data type size * index se)
# suppose u want element stored in no. 2------------------------------> address of 1st element 100+(2x4 data type) = 108 this is how arr works


# break down
# Address = Base address + (Index * Size of each element)
# Address = 100 + (2 * 4)
# Address = 100 + 8
# Address = 108

53

In [14]:
# arr creation -- done
# item accessing 
# item manipulation

### Arr accessing 

In [15]:
ls = [41,33,53,56,64,44,67]
arr[2:5:2]
# start end jump

array([53, 56, 64])

In [16]:
arr.size

7

In [17]:
len(arr)

7

In [18]:
# # i want the items that are less than 50
# ls = [41,33,53,56,64,44,67]
# for i in ls:
#  if i < 50:
#      print(i)

# or method 

arr[arr<50]

array([41, 33, 44])

<!-- new fn-->

In [19]:
# new fn
# gives 1d arr from 0 - 49
arr2 = np.arange(50) 
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [20]:
np.ones(10) # gives 1s arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.ones((10,5)) # it is a 2d array storing 1s 
# here 10 ---row, 5 --- col
# 2d arr is in the form of matrix ek arr ek ander multiple arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.zeros(10) #another fn # gives 0s in arr 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.linspace(1,8,5) 
# in btw 1 -8 fill 5 items the u can wrrite this 

# another example 
# np.linspace(1,50,100) 

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

In [24]:
import random
# random is a module 

In [25]:
random.randint(1,10)
# this fn will give you random value btw 1 - 10

2

In [26]:
random.random()
# this also will give you random value 

0.2622376193121826

In [27]:
ls = ['abi', 'chetan', 'aman']
ls
random.choice(ls)
# this will chosee random ppl from the ls

'abi'

In [28]:
random.choices(ls,k=2)
# this will give 2 names randomly and note the fn is choices.....not choice

['chetan', 'chetan']

In [29]:
random.shuffle(ls)
ls
# items postion is randomly shuffled

['chetan', 'aman', 'abi']

In [30]:
np.random.randint(1,50,10)
# 1-50 random 10 elements

array([ 4, 32, 21, 39, 18,  9,  4, 27, 41, 24])

In [31]:
!python --version 
# this will tell the version 

Python 3.8.10


In [32]:
np.random.randint(1,50,(10,5))
# 1-50 give random elements with 10 row and 5 col --- its a 2d arr

array([[37, 22, 41,  7, 31],
       [31, 44, 31, 20, 24],
       [22, 32, 11, 28,  4],
       [ 6, 29,  8, 29, 20],
       [25, 26,  4, 36, 13],
       [27, 44, 35, 30,  1],
       [31, 32, 38, 14, 10],
       [41, 12, 34, 29, 47],
       [17,  2, 46, 42, 14],
       [ 4,  7,  4,  1,  9]])

In [33]:
arr = np.arange(60)
arr
# its a 1d arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [34]:
# to change the shape
arr.reshape(12,5) # 20,3  #15,4 eg.....

# if u have 20 items u can divide into 10,2     5,4     
# 60   so 15,4   20,3   if you multiple these u get 60 make sure it

# if want to make 3d 
# arr.reshape(10,3,2)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [35]:
arr2 = np.resize(arr,(25,25))
arr2
# if u have less or more items it will adjust automatically randomly
# if the matrix ka multiplication, total no. ofa item usse kam banraha h it leaves, if jayda ban raha h then it will replicate it, in the shape u want but it wont do reshape

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,
         6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
        31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
        11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 

In [36]:
arr2.shape

(25, 25)

In [37]:
arr2.ndim
# its 2d

2

In [38]:
arr2.reshape(625) # 25*25
# this made 25 by 25 arr into 1d arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [39]:
arr2.ravel()
# this will make any D into 1d which is similar to reshape
# arr2.flatten() #ditto as ravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

# Day 2 of learning Numpy


In [40]:
arr = np.random.randint(5,50,100)
arr

array([18, 25, 46, 34, 48, 22, 33, 35, 46, 47, 20, 13, 14, 10, 17, 44, 33,
       28, 44, 22,  7, 40, 19, 32, 32, 37, 16, 48,  7, 45, 41, 13, 34, 45,
       48, 42, 46, 28, 12, 13, 43, 26, 29,  6, 20,  5, 11, 44, 23, 36, 26,
       47, 38, 24, 35, 21, 31, 17, 24, 41, 31, 12, 18, 33, 14, 45, 44, 33,
       25, 24, 17, 23, 10, 23, 40, 39, 30, 32, 37, 39, 23, 28, 17, 25, 48,
       44, 39, 12, 20, 22, 28, 48, 14,  7, 34, 20, 44, 38, 26, 41])

In [41]:
# to find out min 
arr.min()
# arr.max()
# arr.sum()
# arr.mean()


5

In [42]:
arr = np.random.randint(5,50,(4,3))
arr
# 2d arr 4 cross 3

array([[ 7, 22,  6],
       [48, 40, 24],
       [48, 10, 18],
       [26, 27, 11]])

In [43]:
arr.shape

(4, 3)

In [44]:
np.transpose(arr)
arr.T # will perfom the same task no need to write transpose, no need to pass arr
# np.transpose(arr).shape
# row become col vice versa

array([[ 7, 48, 48, 26],
       [22, 40, 10, 27],
       [ 6, 24, 18, 11]])

In [45]:
arr = np.random.randint(2,12,(10,5))
arr
# this is 2d

array([[ 7,  4,  2,  9, 11],
       [10, 11,  9,  2,  9],
       [ 7,  5,  7,  7,  3],
       [ 8,  5,  6,  7,  3],
       [ 7,  2,  2,  4,  6],
       [ 2,  8,  9, 10,  4],
       [ 7,  6,  7,  2,  5],
       [ 9,  8,  2,  5, 10],
       [ 4,  9, 11,  7, 10],
       [ 9,  6,  3,  9,  8]])

In [46]:
# arr.flatten()
# or
# arr.ravel()
# or
# arr.shape then do arr.reshape(50)

# to make it into 1d

In [47]:
# how to fetch the value in 2d acsessing
# so in 2d if u give single eg arr[1] it will give row
# if 3 row from the 2nd then arr[2:5] # [start:stop]
arr = np.random.randint(2,12,(10,5))
arr

array([[ 4,  8,  3,  4,  4],
       [ 7, 10,  6,  3,  6],
       [ 7,  8, 11, 10,  4],
       [ 8,  4,  9,  9,  2],
       [ 7,  5,  8, 10, 10],
       [ 2,  9,  9,  9,  7],
       [ 8, 11,  7,  7,  4],
       [ 3,  4,  5,  6,  6],
       [ 3,  6,  7,  3,  7],
       [10,  8,  2,  6,  3]])

In [48]:
arr[2:5]

array([[ 7,  8, 11, 10,  4],
       [ 8,  4,  9,  9,  2],
       [ 7,  5,  8, 10, 10]])

In [49]:
arr[7:]  # or 7:10

array([[ 3,  4,  5,  6,  6],
       [ 3,  6,  7,  3,  7],
       [10,  8,  2,  6,  3]])

In [50]:
arr[0:10,0:2]
# arr[:,:2]
# arr[0:,0:2]
# arr[:10,:2]
# arr[-10:,:-3]
# arr[-10:,-5:-3]
# all gives same answer
# arr[row start and end,col start and row]

array([[ 4,  8],
       [ 7, 10],
       [ 7,  8],
       [ 8,  4],
       [ 7,  5],
       [ 2,  9],
       [ 8, 11],
       [ 3,  4],
       [ 3,  6],
       [10,  8]])

In [51]:
arr[3:6,2:]

array([[ 9,  9,  2],
       [ 8, 10, 10],
       [ 9,  9,  7]])

In [52]:
arr[0::2,2:]
# arr[row - start:end:jump,col - start:end:jump]

array([[ 3,  4,  4],
       [11, 10,  4],
       [ 8, 10, 10],
       [ 7,  7,  4],
       [ 7,  3,  7]])

In [53]:
# 1D = []
# 2D - [[],[],[]]
# 3D = [2D, 2D, 2D]
# 4D = [3d, 3d , 3d]

In [54]:
arr = np.random.randint(2,50,(5,10,5))
arr
# 5 tables, 10 rows , 5 col, values are from 2 - 50
# array([[[41.. if 3 boxes [[ like this then 3 

array([[[29,  5, 35, 17, 17],
        [32, 39,  3, 38,  8],
        [37, 39, 41, 28, 12],
        [32, 32, 20, 29, 47],
        [49, 38, 15,  9, 23],
        [40,  5, 12,  2, 10],
        [34, 47, 47, 37, 32],
        [39,  4, 34, 10, 24],
        [42, 32, 35,  7, 18],
        [32, 11, 14, 28, 34]],

       [[29, 14, 25, 11, 46],
        [43, 14, 20, 33, 38],
        [40, 13, 45, 16, 45],
        [ 6, 44, 42, 43, 36],
        [31, 49, 17, 33,  9],
        [47, 36, 10, 21, 35],
        [14, 18, 38, 16, 37],
        [12,  2,  3,  8, 41],
        [31, 24, 12, 20,  7],
        [33, 24, 35, 11, 33]],

       [[18, 42, 37,  8, 34],
        [45, 39, 40, 47, 40],
        [ 2,  7, 17,  2, 11],
        [37, 37, 27, 10,  6],
        [18, 38, 15,  9, 34],
        [29, 15, 43, 31, 37],
        [33, 12, 12,  8, 29],
        [30,  4, 26, 27, 21],
        [29, 21, 20, 45, 49],
        [42, 10,  4, 47, 35]],

       [[18, 49, 13, 44, 16],
        [34, 43, 26, 24, 39],
        [30, 22, 23,  2, 11],
    

In [55]:
arr.shape

(5, 10, 5)

In [56]:
arr.ndim

3

In [57]:
arr[0] 
# the value i put 3rd table will give 

array([[29,  5, 35, 17, 17],
       [32, 39,  3, 38,  8],
       [37, 39, 41, 28, 12],
       [32, 32, 20, 29, 47],
       [49, 38, 15,  9, 23],
       [40,  5, 12,  2, 10],
       [34, 47, 47, 37, 32],
       [39,  4, 34, 10, 24],
       [42, 32, 35,  7, 18],
       [32, 11, 14, 28, 34]])

In [58]:
# i want the elements   12, 32, 10, 44, 44, 22 from the last of 1st table
# arr[8:0,2:0] doubt ask later 

In [59]:
arr

array([[[29,  5, 35, 17, 17],
        [32, 39,  3, 38,  8],
        [37, 39, 41, 28, 12],
        [32, 32, 20, 29, 47],
        [49, 38, 15,  9, 23],
        [40,  5, 12,  2, 10],
        [34, 47, 47, 37, 32],
        [39,  4, 34, 10, 24],
        [42, 32, 35,  7, 18],
        [32, 11, 14, 28, 34]],

       [[29, 14, 25, 11, 46],
        [43, 14, 20, 33, 38],
        [40, 13, 45, 16, 45],
        [ 6, 44, 42, 43, 36],
        [31, 49, 17, 33,  9],
        [47, 36, 10, 21, 35],
        [14, 18, 38, 16, 37],
        [12,  2,  3,  8, 41],
        [31, 24, 12, 20,  7],
        [33, 24, 35, 11, 33]],

       [[18, 42, 37,  8, 34],
        [45, 39, 40, 47, 40],
        [ 2,  7, 17,  2, 11],
        [37, 37, 27, 10,  6],
        [18, 38, 15,  9, 34],
        [29, 15, 43, 31, 37],
        [33, 12, 12,  8, 29],
        [30,  4, 26, 27, 21],
        [29, 21, 20, 45, 49],
        [42, 10,  4, 47, 35]],

       [[18, 49, 13, 44, 16],
        [34, 43, 26, 24, 39],
        [30, 22, 23,  2, 11],
    

In [60]:
arr[0]

array([[29,  5, 35, 17, 17],
       [32, 39,  3, 38,  8],
       [37, 39, 41, 28, 12],
       [32, 32, 20, 29, 47],
       [49, 38, 15,  9, 23],
       [40,  5, 12,  2, 10],
       [34, 47, 47, 37, 32],
       [39,  4, 34, 10, 24],
       [42, 32, 35,  7, 18],
       [32, 11, 14, 28, 34]])

In [61]:
arr2 = arr[0]
arr2

array([[29,  5, 35, 17, 17],
       [32, 39,  3, 38,  8],
       [37, 39, 41, 28, 12],
       [32, 32, 20, 29, 47],
       [49, 38, 15,  9, 23],
       [40,  5, 12,  2, 10],
       [34, 47, 47, 37, 32],
       [39,  4, 34, 10, 24],
       [42, 32, 35,  7, 18],
       [32, 11, 14, 28, 34]])

In [62]:
arr2[8:,2:]

array([[35,  7, 18],
       [14, 28, 34]])

In [63]:
arr[:1:,8::,2::] #only for 3D to slice

array([[[35,  7, 18],
        [14, 28, 34]]])

In [64]:
# if i want last row of every table 
arr[:,9:,:]

array([[[32, 11, 14, 28, 34]],

       [[33, 24, 35, 11, 33]],

       [[42, 10,  4, 47, 35]],

       [[38, 12, 31, 44, 48]],

       [[16, 43, 13, 23,  3]]])

In [65]:
arr = np.array([7,5,9])
arr

array([7, 5, 9])

In [66]:
# arr.min()
arr.max()

9

In [67]:
arr.argmax()
# arr.argmin()
# what is the diff btw argmax and max
# max - retuen max item
# argmax - retuns index pos of the max item

2

In [68]:
arr.sort()
arr
# this sort in accending 

array([5, 7, 9])

In [69]:
arr[::-1] # to print in the reverse order # try to undersatnd this again

array([9, 7, 5])

In [70]:
arr.argsort()

array([0, 1, 2], dtype=int64)

In [71]:
arr  #[0, 1, 2] now match this with below value, its the index of the array given below 

array([5, 7, 9])

In [72]:
# diff btw sort and argsort
# sort - gives the value in accending order
# argsort - gives the postion in the array given

In [73]:
arr = np.random.randint(2,12,(10,5))
arr

array([[ 5,  6,  7, 11, 11],
       [ 4, 11,  9, 11, 11],
       [ 4,  7,  9,  6, 10],
       [10, 11,  6,  7,  4],
       [ 7,  8,  6,  7,  3],
       [ 4,  6,  5, 10,  5],
       [ 9, 10,  8,  7,  9],
       [10,  8,  7,  9,  4],
       [ 8, 10,  6,  5,  6],
       [ 2,  4,  7,  7,  2]])

In [74]:
np.unique(arr) # give all the unique itmes in this fn

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [75]:
arr = np.random.randint(2,250,200)
arr

array([169, 156, 168, 182, 232, 167,  70,  78, 174, 217,  77,  95, 213,
       129, 106,  76,  23,  36,  79, 240, 196,  87,  42,  11, 122, 157,
        65, 233,  11,  32, 223, 102,  19, 247,  42,  71,  28,  43,  24,
       131, 204, 139, 238,  99, 237, 249, 245, 129,  88, 247, 241, 180,
       118, 227, 168,   4, 237,  85, 167, 228, 197, 136, 106, 132,  92,
       195,  27,  77, 215, 189, 248, 204, 110, 134,  94,  31,  66, 158,
       144, 108, 112, 147, 155,  11, 160, 126, 166,  44,  89, 194,  91,
        34, 119, 232, 190,  51, 129, 158,  42,  72, 101,  56, 210,  52,
       219,  26, 118, 182, 120, 115, 104,  80, 121, 214, 165, 242, 199,
       246,  32, 140, 208,  43,  64,  23, 189,  46, 177, 146,  30,  48,
       131, 132,  51,  78, 213, 122, 147,  51, 200,  37, 223,   2, 164,
       156, 165,  18, 165, 200,   6, 134, 167,  12, 129, 227,   2,  99,
        53, 247, 116, 181,  72, 235, 160,  76,  82,   5, 106,  82, 140,
        57, 148,  73, 169,  27, 195,  69, 182, 191, 190, 249, 12

In [76]:
arr.var() #var means varients 

4995.586399999999

In [77]:
np.median(arr)

131.5

In [78]:
arr.std() #standard division

70.67946236354659

In [79]:
np.sqrt(25) #to find sq root

5.0

# ---------------------------------------End of Numpy----------------------------